dbt_project:
  target: test
  
  outputs:
    test:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('HOME') }}/dbt/include/keyfile.json"
      project: consulting-project-1
      dataset: e_commerce
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
